name: Build and Test Monolith Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # You can specify the versions of Node.js you want to test against

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Build and test client
      - name: Install client dependencies
        working-directory: client
        run: npm install

      - name: Build client
        working-directory: client
        run: npm run build

      - name: Run client tests
        working-directory: client
        run: npm test

      # Start and test server
      - name: Install server dependencies
        working-directory: server
        run: npm install

      - name: Run server
        working-directory: server
        run: npm run start

      - name: Run server tests
        working-directory: server
        run: npm test